Create New User Command and Test
MyMediaMagnet/multi-tenant-laravel pull request #18
Opened 2018-07-19 21:22 UTC by BrandonSPT

2018-07-19 21:25 UTC, MyMediaMagnet commented on tests/Unit/ArtisanTest.php
> +
I think this should read `CreateUser[asks, anticipates]`

2018-07-19 21:26 UTC, MyMediaMagnet commented on tests/Unit/ArtisanTest.php
> +
Nevermind...singular seems to be how I have it.  You only need to add `ask` once however.

2018-07-19 21:28 UTC, BrandonSPT commented on tests/Unit/ArtisanTest.php
> +
Fixed

2018-07-20 17:48 UTC, MyMediaMagnet commented on src/app/Commands/CreateUser.php
> +
I know you'll think this is picky, but lets get rid of the extra whitespace here :).

2018-07-20 17:49 UTC, MyMediaMagnet commented on src/app/Commands/CreateUser.php
> +
extra line break

2018-07-20 17:49 UTC, MyMediaMagnet commented on tests/Unit/ArtisanTest.php
> +
line breaks

2018-07-20 17:49 UTC, MyMediaMagnet requested changes
Just formatting stuff...all looks good though

2018-07-23 20:53 UTC, merged